// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyqcgtbjoehyeieulrtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cWNndGJqb2VoeWVpZXVscnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzODcyMTIsImV4cCI6MjA0OTk2MzIxMn0.Bx1BxguxESb_sIgSY8921Iz-T_INTXR7K1ZmnR0u_SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);